services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      GDRIVE_FOLDER: ${GDRIVE_FOLDER}
      GAPI_KEY: ${GAPI_KEY}
      TITLE: ${TITLE}
    volumes:
      - ./data:/app/data
      - ./thumbnails:/app/thumbnails
